---
title: "PCA"
author: "Dario Alvarado"
date: "2023-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Paquetes

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(FactoMineR)
library(factoextra)
library(rio)
library(parameters)
library(ade4)
```

### Datos

```{r}
data("doubs")
vars <- doubs$env
head(vars)
```

### PCA

```{r}
vars_pca <- PCA(vars, graph = FALSE)
vars_pca
```

```{r}
summary(vars_pca)
```

```{r}
sitios <- data.frame(vars_pca$ind$coord)
sitios
```

```{r}
export(sitios, "datos/pca_sitios.csv")
```

```{r}
valores <- get_eigenvalue(vars_pca)
valores
```

```{r}
fviz_eig(vars_pca, addlabels = TRUE)
```

```{r}
fviz_pca_var(vars_pca, col.var = "cos2", repel = TRUE, gradient.cols = c("blue", "yellow", "red"))
```

```{r}
fviz_cos2(vars_pca, choice = "var", axes = 1:2)
```

```{r}
fviz_contrib(vars_pca, choice = "var", axes = 1:2)
```

```{r}
fviz_pca_var(vars_pca, col.var = "contrib", repel = TRUE, gradient.cols = c("blue", "yellow", "red"))
```

```{r}
fviz_cos2(vars_pca, choice = "ind", axes = 1:2)
```


```{r}
fviz_contrib(vars_pca, choice = "ind", axes = 1:2)
```

```{r}
fviz_pca_ind(vars_pca, col.ind = "contrib", repel = TRUE, gradient.cols = c("blue", "yellow", "red"), pointsize = "contrib")
```

```{r}
fviz_pca_biplot(vars_pca,
                col.ind = "gray15",
                col.var = "blue") +
  theme_classic() +
  labs(title = "Análisis de Componentes Principales")
```

```{r}
ggsave("pca_biplot.jpg")
```

```{r}
pca.parameters <- principal_components(vars, n = 3)
pca.parameters
```

```{r}
class(pca.parameters)
```

```{r}
export(pca.parameters, "datos/pca_variables.csv")
```

```{r}
summary(pca.parameters)
```

```{r}
plot(pca.parameters, type = "line")
```

